name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js with PNPM
        uses: pnpm/setup-pnpm@v1
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Build and Test
        run: pnpm run build
