name: Publish NPM Package on Release

on:
  release:
    types: [created] # Déclenche l'action lorsqu'une nouvelle release est créée

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build package
        run: npm run build

      - name: Publish package to NPM
        run: npm publish --access public
        env:
          AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
