name: Publish NPM Package on Release

on:
  push:
    branches:
      - 'feat/pipeline-deploy'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
          run_install: |
            - recursive: true

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build package
        run: npm run build

      - name: Publish package to NPM
        run: npm publish --access public
        env:
          AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
